---
title: "HCI Data Code book"
author: "Maeve Wickham"
date: "December 11, 2018"
output: html_document
---
This codebook describes the process of tidying the UCI HAR Dataset. 

hartidy.txt is the tidy output file from the run_analysis R script. This cleaned datafile has 180 observations on 69 variables. 

The variables included in the hartidy.txt dataset are:

id = participant ID, ranging from 1 to 30. 
activitytype = a descriptive, factor variable that describes the activity being performed.
activity = a numeric variable for the activity being performed. 

smartphone measurements = numeric, with the naming convention as follows: 

-- prefix: time = time domain; freq = frequency domain 

-- body = body acceleration signal;  gravity = gravity acceleration signal 

-- accelerometer = acelerometer data; gyroscope = gyroscope data

-- jerk = jerk signal; magnitude = magnitude 

-- mean = mean; std = standard deviation

-- suffix = x/y/z which indicates the smartphone axis in the X, Y and Z directions

FULL MEASUREMENT LIST: 

timebodyaccelerometermeanx  

timebodyaccelerometermeany

timebodyaccelerometermeanz          

timegravityaccelerometermeanx

timegravityaccelerometermeany          

timegravityaccelerometermeanz

timebodyaccelerometerjerkmeanx

timebodyaccelerometerjerkmeany

timebodyaccelerometerjerkmeanz 

timebodygyroscopemeanx

timebodygyroscopemeany  

timebodygyroscopemeanz

timebodygyroscopejerkmeanx 

timebodygyroscopejerkmeany

timebodygyroscopejerkmeanz

timebodyaccelerometermagnitudemean

timegravityaccelerometermagnitudemean 

timebodyaccelerometerjerkmagnitudemean

timebodygyroscopemagnitudemean    

timebodygyroscopejerkmagnitudemean

freqbodyaccelerometermeanx         

freqbodyaccelerometermeany

freqbodyaccelerometermeanz   

freqbodyaccelerometerjerkmeanx

freqbodyaccelerometerjerkmeany         

freqbodyaccelerometerjerkmeanz

freqbodygyroscopemeanx                 

freqbodygyroscopemeany

freqbodygyroscopemeanz                 

freqbodyaccelerometermagnitudemean

freqbodyaccelerometerjerkmagnitudemean

freqbodygyroscopemagnitudemean

freqbodygyroscopejerkmagnitudemean 

timebodyaccelerometerstdx

timebodyaccelerometerstdy              

timebodyaccelerometerstdz

timegravityaccelerometerstdx           

timegravityaccelerometerstdy

timegravityaccelerometerstdz           

timebodyaccelerometerjerkstdx

timebodyaccelerometerjerkstdy          

timebodyaccelerometerjerkstdz

timebodygyroscopestdx                  

timebodygyroscopestdy

timebodygyroscopestdz                  

timebodygyroscopejerkstdx

timebodygyroscopejerkstdy              

timebodygyroscopejerkstdz

timebodyaccelerometermagnitudestd     

timegravityaccelerometermagnitudestd

timebodyaccelerometerjerkmagnitudestd 

timebodygyroscopemagnitudestd

timebodygyroscopejerkmagnitudestd     

freqbodyaccelerometerstdx

freqbodyaccelerometerstdy              

freqbodyaccelerometerstdz

freqbodyaccelerometerjerkstdx          

freqbodyaccelerometerjerkstdy

freqbodyaccelerometerjerkstdz          

freqbodygyroscopestdx

freqbodygyroscopestdy                  

freqbodygyroscopestdz

freqbodyaccelerometermagnitudestd   

freqbodyaccelerometerjerkmagnitudestd

freqbodygyroscopemagnitudestd         

freqbodygyroscopejerkmagnitudestd


The following excerpt comes from the readme file in the raw dataset: 

"Original Experiment Information
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details.

For each record it is provided:
Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
Triaxial Angular velocity from the gyroscope.
A 561-feature vector with time and frequency domain variables.
Its activity label.
An identifier of the subject who carried out the experiment.
The dataset includes the following files:
'README.txt'

'features_info.txt': Shows information about the variables used on the feature vector.

'features.txt': List of all features.

'activity_labels.txt': Links the class labels with their activity name.

'train/X_train.txt': Training set.

'train/y_train.txt': Training labels.

'test/X_test.txt': Test set.

'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent.

'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.

'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis.

'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration.

'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second.

Notes:
Features are normalized and bounded within [-1,1].
Each feature vector is a row on the text file.
For more information about this dataset contact: activityrecognition@smartlab.ws

Feature Selection 

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation
mad(): Median absolute deviation 
max(): Largest value in array
min(): Smallest value in array
sma(): Signal magnitude area
energy(): Energy measure. Sum of the squares divided by the number of values. 
iqr(): Interquartile range 
entropy(): Signal entropy
arCoeff(): Autorregresion coefficients with Burg order equal to 4
correlation(): correlation coefficient between two signals
maxInds(): index of the frequency component with largest magnitude
meanFreq(): Weighted average of the frequency components to obtain a mean frequency
skewness(): skewness of the frequency domain signal 
kurtosis(): kurtosis of the frequency domain signal 
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean

The complete list of variables of each feature vector is available in 'features.txt' "

The run_analysis.R script performs the following on the raw data to transform the dataset to a tidy one:

1. Merge the training and test sets to create one data set

The run_analysis.R script under this step first downloads the raw data from the provided link, then loads in all 
required datasets. After loading, the variables are renamed based on the activity/feature (which is done with 
"clean names" for future manipulation of the data in a later step.) The columns from the test and train datasets 
(y_test/train, x_test/train, and subject_test/train) are bound together, and then the rows are appended to create 
one dataset called "merged".

2. Extract only the measurements on the mean and standard deviation for each measurement.

From here, the script searches through the column names to select only the columns that contain the words "mean" or "std", in addition to the activity type and subject ID. This is stored in a new dataset called "meanStd".

3. Use descriptive activity names to name the activities in the data set

The merged, mean and standard deviation dataset ("meanStd") is then merged with the activity labels to provide the
descriptive activity labels. Note: I retained the numeric version of the activity type in the case of future regression 
modelling, in which case a numeric variable would be useful. 

4. Appropriately label the data set with descriptive variable names.

The names of the merged, mean and std dataset were then cleaned up (e.g., periods removed, lower case lettering), 
and shorthand terms were elaborated upon (e.g., mag --> magnitude). 

5. From the data set in step 4, create a second, independent tidy data set with the average of each variable for each activity and each subject

Finally, the tidy dataset ('hartidy') is created by aggregating the means for each feature, per person per activity. 
The tidy dataset is then ordered by id and activity to present a sorted, cleaned dataset. 

The final result is stored in "hartidy" and output to file 'hartidy.txt'.

